### ISSUE TITLE
Kritike trenutnog poretka lekcija

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#1]
Stara ideja što se tiče organizacije rada i poretka lekcija: [(link)](https://github.com/tmamic/makoto-japanski/files/1724727/plan.pdf)
Za sve ovo implementirati treba malo više mašinerije u pozadini nego što trenutno imamo, ali može nam poslužiti kao dobra polazišna točka. Poredak lekcija kako sam ga napisao ovdje je dobrim dijelom provođen u praksi ove godine uz neke manje praktične izmjene pa će nam i povratne informacije ovogodišnje početne grupe biti korisne.

ToDo:
* pročitati poredak lekcija i ciljeve u planu
* pogledati dosad odrađene lekcije na google driveu [(link)](https://drive.google.com/drive/folders/0Bz3oODAn8tywZURsOUtrVXRWODQ)
* kritizirati i jedno i drugo, dati prijedloge za promjene/poboljšanje

**Comment by tmamic** [comment]
Moji prijedlozi i pitanja:

* zadnje 3 lekcije pod 'imenice' presložiti u dvije:
    * imenice + pokazne zamjenice + の, や, と
    * osobne zamjenice, imena i titule (oslovljavanje ljudi)

* zamijeniti poredak predikatnom i opisnom obliku pridjeva?
    * ako je predikatni prvi, lijepo se veže na だ od lekcije prije
    * ako je prvi opisni, jasnije je da su to pridjevi i な ima smisla

* presložiti dio o prilozima:
    * prilozi
    * mjesto (ne ovisi ni o čemu prije)
    * količina i brojači (ovisi o brojevima, možda je to velika lekcija)
    * vrijeme (ovisi o brojačima)
    * čestice na kraju rečenice i postavljanje pitanja (ovisi o svim priložnim oznakama) - možda bi bilo dobro učiti pitanja paralelno s izjavnim rečenicama? nisam nikad probao...

* rastaviti izraze s て i い oblicima na dvije lekcije - to je ogromno područje i ionako ga nećemo cijelog raditi odjednom

* dio sa spojevima treba apdejtati novom organizacijom koja mi se čini da je dobro uspjela ove godine

* trebamo li staviti 漢字 ranije?

* trebamo li napredne glagolske oblike prije složenih rečenica?

**Comment by zludosan** [comment]
-  Ne mogu ništa pametno komentirati za sad za sam **poredak lekcija**, budući da sam sama učila te stvari "na vrat na nos" bez ikakvog logičnog slijeda i jednostavno nisam pametna po tom pitanju. Svaki moj komentar vezan u to sad bi bio...nagađanje.

- Mislim da **kanji** treba staviti što ranije, odmah nakon kane, da se na svakog lekciji nauči barem jedan ili dva kanji-ja koji su jednostavni za napisat i koji se često ponavljaju u zadaćama.(note za kasnije: napisati prijedlog kanji-ja za svaku lekciju).

- Bolje imati **složene rečenice prije naprednih glagolskih oblika** jer će na taj način bolje shvaćati njihovo mjesto u rečenici.

**Comment by tmamic** [comment]
I nagađanje je vrlo korisno kad imaš razlog zašto nešto misliš.

Igram se idejom da svaki tjedan ima uz gramatiku i praktičnu situaciju (kao što udžbenici imaju u lekcijama), ali takvu da se ta gramatika da iskoristiti na neki zgodan način. Možda bismo mogli i kanji ugraditi u to nekako, ali trebat će pomnog planiranja.

**Comment by zludosan** [comment]
U vezi .tex file-ova pod "radionice", ima samo jedan za početni i jedan za napredni. A znam da im svaki tjedan daješ zadaću i da ih imaš više. Ih možeš isto gore uploadati? Hoću vidjeti koje se riječi najčešće ponavljaju pa da od toga krenem raditi neki početni popis kanji znakova.

**Comment by tmamic** [comment]
Ovdje je trenutni izvor materijala ([link](https://drive.google.com/drive/u/0/folders/0Bz3oODAn8tywbkoxMGM5ZGdqb1U)) za radionice. Možda fali poneki listić, ali ima ih dovoljno za sastaviti sliku koje riječi koristimo najčešće.

Nije mi uopće gnjavaža, ali ovdje sam mislio stavljati samo nove stvari koje uredimo, iako sam čini mi se uploadao neke stare i dosta loše listiće isto, dok sam sve isprobavao.

**Comment by nyaamee** [comment]
Definitivno se slažem da bi se trebalo ranije uvoditi kanjije, no možda ne odmah nego ostaviti koji tjedan za navikavanje na novo pismo. Kako je to dosta opširna tema radi preglednosti sam otvorila novi issue posvećen kanjijima na radionicama, primarno redosljedu kojim će se obrađivati, pa pogledajte i tamo.

**Comment by tmamic** [comment]
S obzirom da je ovdje razgovor zamro, ako nitko nema daljnjih primjedbi, u repo sam dodao tablicu ([link](https://github.com/Makoto-hr-jp/makoto-japanski/files/1747632/001_popis_tema.pdf)) koju bismo trebali popuniti, a za to ću otvoriti i novi zadatak.
