### ISSUE TITLE
Drugi dio い oblika za početnike

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#10]
Za brzi pregled: ([link](https://github.com/Makoto-hr-jp/makoto-japanski/files/1818525/016_i_2.pdf))

Dodajemo još malo osnovnih funkcionalnosti na い oblik. Prije smo u obliku brzog pregleda radili dosta različitih upotreba, ali mislim da je to negativno utjecalo na ljude pa sam ovaj put malo usporio い i て. Čini mi se da ima dobar utjecaj.

S obzirom da ovaj tjedan sve kasni barem 2 dana, ako stignete do sutra ujutro nešto napisati - super, ako ne, promjene će zaživjeti od sljedeće sezone. Unatoč tome, samo tipkajte :)

**Comment by zludosan** [comment]
Listić je sasvim solidan. Jednostavan i jasan. 
Koji je zadatak za vježbe? Prvo sam mislila da je mijenjati riječi i rečenice tako da koriste たい, ali neke rečenice već jesu u tom obliku...?Oo
Možda bi bilo dobro spomenuti da se češće kaže " 行きたくないです", nego "いきたくありません".  Al to ne mora biti na listiću...

**Comment by tmamic** [comment]
Nešto sam im pričao o ないです vs ありません kad smo radili pridjeve, tako da im to nije novo. Što se tiče razlike, stvar je u pristojnosti više nego u učestalosti. ありません je pristojno, ないです je jedna od onih stvari koje su bile krive, ali ih je dovoljno ljudi koristilo pa su postale točne.

**Comment by zludosan** [comment]
A, dobreko onda.

**Comment by tmamic** [comment]
Ipak sam napisao. Valja misliti i na one koji neće biti na satu.
