### ISSUE TITLE
Uputa za izradu lekcija za radionice

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#11]
Moj prijedlog se nalazi ovdje [(link)](https://github.com/Makoto-hr-jp/makoto-japanski/files/1871130/002_uputa_za_izradu.pdf). Dosad sam konzistentno radio samo točke 2 i 4, a 1 bih sažeo na jedno mjesto za sve lekcije. Nakon par iteracija promjena, zaključio sam da je to neučinkovito jer sav sadržaj lekcije nije grupiran na jedno mjesto, iako je smisleno da cijeli paket bude zajedno. Više o razlozima i detaljima u subotu. Dajte svoje komentare na prijedlog iznad kad vam nešto padne na pamet - cilj je da svi pakiramo svoje lekcije na isti način.

**Comment by zludosan** [comment]
Bi mogel malo nadopuniti opet Wiki  - Popis i sadržaj tema po tjednima da vidim lakše koje lekcije su sljedeće? Bar imena sljedećih 5 lekcija...

**Comment by tmamic** [comment]
Evo jesam. Inače radna verzija toga nalazi se ovdje ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/release/001_popis_tema.pdf)).
