### ISSUE TITLE
Pregled kondicionala

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#12]
Listić koji radimo ove subote u 17:30 ([link](https://github.com/Makoto-hr-jp/makoto-japanski/files/1874664/019_kondicionali.pdf)).

Kao i obično, trebam komentare na sadržaj, jasnoću, primjere, sve što vam padne na pamet.

**Comment by zludosan** [comment]
- Pobjegla su ti slova na tablici kod ば kondicional -> 五段.
- Na drugoj stranici rečenica di je Rodrigo je stisnuta nekam prema gore.
- Na drugoj stranici 言えば → 言いや, ili すれば → すりゃ.   < - Makneš ovaj zarez koji je uletio prije "ili"

Ovo je baš dobar listić, lako razumljivo. A ima i fora stvari unutra kak su さえ i のに na kraju rečenice.

**Comment by tmamic** [comment]
Za ovo prvo je namjerno, da naglasim da se radi o zvuku _e_, ne o hiragana znaku え.

Rodrigo je stisnut jer nema furigane. Čini ti se da je stisnuto jer inače ostaje prostor za furiganu. Možda bi bilo dobro da svejedno ostavim razmak iako je nema?

E, vidiš :)

**Comment by zludosan** [comment]
> Za ovo prvo je namjerno, da naglasim da se radi o zvuku e, ne o hiragana znaku え.

Aha! Hmmm...malo je nespretno, ali to je uvijek tak kad se pišu stvari u tablice.
Haha, sad vidim nekaj. Nisam znala da se だ mjenja u ならば, ja bi se tu uvijek izvlačila i promjenila u だったら. :D 

Si ti to sam sebi dal "Thumbs Up"?

**Comment by tmamic** [comment]
Da, iako to nije bio originalni plan...
