### ISSUE TITLE
[lekcija] Hiragana

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#13]
Dosadašnji materijali:
* ([detaljni pregled](https://drive.google.com/open?id=0Bz3oODAn8tywNjNfallVSVVNdDQ))
* ([prvi listić ove sezone](https://drive.google.com/open?id=0Bz3oODAn8tywNnNrNVRGRGpNOG8))

Nova lekcija nalazi se ovdje ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/001_hiragana/release/)).

Bilo bi zgodno kao dodatne materijale uključiti i pokoji video ljudi kako pišu i slike raznih rukopisa (google slike za 手書きひらがな), naravno neki DZ koji će ljude natjerati da puno traže po tablici.

**Comment by tmamic** [comment]
Osnovni tekstovi su natipkani, @Erebus25 molim te baci oko.

**Comment by Erebus25** [comment]
U uvodu -  "u je zamjetno pomaknuo prema naprijed" --> "pomaknut" ili "se"
U hiragan - cijeli teskt je napisan kao strucna literatura, to nitko nece procitat
 - gdje su tablice T1 i T2?

**Comment by tmamic** [comment]
To su tablice hiragane i katakane iz jednog drugog skroz starog dokumenta koji nema direktne veze s radionicama. Reciklirao sam dio u kojem je objašnjena hiragana kao dodatni materijal.

Morat ću razmisliti o svojim postupcima.

**Comment by tmamic** [comment]
Samo da budem siguran, gledao si ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/001_hiragana/release/000_hiragana.pdf) i ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/001_hiragana/release/001_hiragana_ciljevi_i_napomene.pdf)).

**Comment by Erebus25** [comment]
Ne, gledao sam fajlove linkane u prvoj poruci.

   - (detaljni pregled
   <https://drive.google.com/open?id=0Bz3oODAn8tywNjNfallVSVVNdDQ>)
   - (prvi listić ove sezone
   <https://drive.google.com/open?id=0Bz3oODAn8tywNnNrNVRGRGpNOG8>)

Pogledam još i te koje si sad linkao.

Dana 9. svibnja 2018. u 13:08 Tomislav Mamic <notifications@github.com> je
napisao/la:

**Comment by Erebus25** [comment]
Ovaj s napomenama mi se čini ok, ova priča oko "p" mi je čudno stavljena u rečenicu, ali ok je za napomenu.

Na drugom listicu tablica mi se ne svida, more imaju svoj poredak, kao i abeceda, zar ne?
Isto bih ju obrnuo da bude vise japanski i izbacio onaj "j(y)" i samo stavio "y". 
Daleko je bolji od one stare verzije, ali i dalje mi se čini... nepotreban.
Jel to dolazi nakon što bi trebali već naučit pisat hiraganu?

**Comment by tmamic** [comment]
Imaš pravo što se tiče poretka mora, ali na internetu je popularno zgurati naprijed ove pune stupce pa sam se poveo za trendom. Vratio sam na standardni poredak. Orijentaciju tablice neću promijeniti jer je poanta da se snađu po latinici na okviru.

Promijenio sam j(y) -> y.

Što je točno nepotrebno? Teško mi je pogoditi koji točno dijelovi ti smetaju, ali prilično sam siguran da nije cijeli listić.

To dolazi poslije tjedna u kojem im je dz doma proučiti o japanskom općenito i početi učiti hiraganu, a nakon toga slijedi tjedan u kojem se zapravo očekuje da je intenzivno uče.

**Comment by Erebus25** [comment]
Ne znam, teško mi se zamislit kao osoba koja uči hiraganu i hoće li joj to
pomoći ili samo smanjiti motivaciju.
Kako ti se činilo kad ste to radili ove godine?

Dana 9. svibnja 2018. u 15:13 Tomislav Mamic <notifications@github.com> je
napisao/la:

**Comment by Erebus25** [comment]
Na strani 2, fusnota počinje malim slovom.
Inače se čini ok.

Dana 9. svibnja 2018. u 16:24 Tomislav Mamic <notifications@github.com> je
napisao/la:

**Comment by tmamic** [comment]
Fusnota popravljena. ToDo su DZ i slike rukopisa.

**Comment by zludosan** [comment]
Dodala sam rukopis_6 sa kurzivom.

**Comment by tmamic** [comment]
@Erebus25 Izmijenjen tekst o morama na listiću da ne bude pretrpan tehničkim detaljima, onaj detaljniji prenesen u dodatne pričice, molim provjeru.

**Comment by Erebus25** [comment]
Link za novu lekciju ne radi

sub, 22. ruj 2018. u 19:45 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
@Erebus25 ups, broj lekcije je pomaknut u odnosu na onda ([link](https://github.com/Makoto-hr-jp/makoto-japanski/tree/master/radionice/pocetni/lekcije/002_hiragana/release)).

**Comment by tmamic** [comment]
@Erebus25 ^^

**Comment by Erebus25** [comment]
Što treba tu? Ove s 002, rukopise ili sve?

pon, 1. lis 2018. u 08:31 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
@Erebus25 listić, ciljevi i napomene. Možeš vidjeti prema zadnjem komitu što je kad mijenjano.

**Comment by Erebus25** [comment]
Ciljevi ok.
listić - mislim da ti ne treba "O detaljima kasnije." to im kažeš, a ako
čitaju sami će nać
možda ne započet odlomke istim rijecima
nisam nasao na sto se odnosi 1. fusnota, takoder su brojevi 2. i 3. fusnote
zamijenjeni


pon, 1. lis 2018. u 10:08 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
@Erebus25 
- popravljena 1. fusnota (dio koji je bio označen slučajno izbrisan u promjenama)
- maknuto _o detaljima kasnije_
- početak drugog odlomka upristojen
- popravljeni brojevi fusnota

**Comment by Erebus25** [comment]
2. odlomak - "Zbog same... je nemoguće NAPISTI...

uto, 2. lis 2018. u 07:54 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
@Erebus25 popravljeno :)

**Comment by Erebus25** [comment]
Ostalo izgleda ok

uto, 2. lis 2018. u 08:33 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
U tom slučaju natrag u ropotarnicu povijesti :)
