### ISSUE TITLE
[lekcija] Imenice i pokazne zamjenice

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#14]
Ciljevi:
* naučiti neke imenice iz prirode/životinje/voće (recimo 20ak riječi)
* posvojna čestica の
* pokazne zamjenice これ, それ, あれ i この, その, あの
* naglasak na korištenje hiragane

**Comment by zludosan** [comment]
Lekcija je commitana, al trebam pomoć.
Em sa lekcijom em s Latexom. Neke stvari mi ne izgledaju kako bi trebale.
Tablica na početku čudno izgleda i neznam kak da preradim \juuyou da mi funkcionira za dulji tekst.

**Comment by tmamic** [comment]
Samo pitaj redom, sve ćemo riješiti. Ovaj \juuyou radi tako da napravi prostor za tekst koji je [toliko] odmaknut od lijevog i desnog ruba. Vidim da si stavila 200pt što je puno odmaka, znači da ti na sredini ostane malo mjesta za tekst. Ako ga staviš na recimo 20pt, imat ćeš dosta šire polje za tekst. Prepravio sam \juuyou tako da centrira tekst, možda će ti to malo pomoći.

U tablici sva polja moraju biti definirana pa čak i prazna, zato ti je na kraju poremetilo zadnje polje. Ako samo dodaš još & na kraj tako da cijeli red bude ispunjen, bit će ok. E sad, s obzirom da je ova lekcija među prvima, ja bih potpuno odustao od kanđija. Vjerojatno si potrošila dosta vremena na tipkanje sve furigane, ali mislim da se ljudi neće baš snaći u tome, da će im biti pomalo strašno.

**Comment by Erebus25** [comment]
Ovi prijevod s "od", nisu u duhu hrvatskog, a već ima "boja od cvijeta" da se shvati poanta pa bih ih promijenu u lišće drveta/ća, Tanakina knjiga i prozor sobe. 
Katakanu bih izbacio ili stvarno minimizirao, ako to ide drugi vikend, jedva će još i hiraganu hvatat.
Dodao bih koreno -> kono, ili je to više zabilješka za naglasit nego za papir?,

**Comment by zludosan** [comment]
To ide u drugi vikend?
@Erebus25 koreno -> kono. U pravu si tu, tako sam i htjela napisati da bude jasno.
Idem ja prvo maknuti sve kanđije, pa maknuti "od", pa staviti koreno soreno...

P.S. Znate ono kad dobijete gro teksta na japanskom sa pun kufer kanđija, ali svaki ima furiganu i onda to sve pročitate do kraja i osjećate se ko faca. :D

**Comment by Erebus25** [comment]
Je, sjećam se tih dana. Sad me samo frustriraju jer ne znam pročitat
kanjije :)

Dana 28. travnja 2018. u 14:51 zludosan <notifications@github.com> je
napisao/la:

**Comment by zludosan** [comment]
1. Zašto se radi lekcija posvojna zamjenica の, ako je to već obrađeno? Upravo gledam papir...
2. Jel pod tu lekciju možda trebalo i pisati kako se rade imenice? :)

**Comment by zludosan** [comment]
3. Ispravila sam ovo i stavila pod lekcija 003.

**Comment by tmamic** [comment]
1. To po novom planu nije obrađeno sve do tvoje lekcije :)
2. Pod tu lekciju bi ušlo nešto osnovno o imenicama (da su nepromjenjive, nema roda broja i padeža itd, neke osnovne simpa stvari)
4. Nije bitno da koristiš samo te riječi, ali je bitno da odabereš riječi koje su korisne i česte, pa će preklapanje biti veliko. Imaš i popis tema po lekcijama ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/release/001_popis_tema.pdf)) pa slobodno koristi vokabular za koji misliš da bi se trebao pojaviti u prethodnim temama. Dobro je da se pojavljuju nove riječi i to nije ništa čega se treba bojati, dok se god radi o riječima koje bi početnicima mogle biti korisne.

**Comment by tmamic** [comment]
* Točan prijevod これ, それ i あれ na hrvatski je _ovo_, _to_ i _ono_. Mislim da je u redu forsirati taj prijevod. * Opis upotreba odmah ispod tablice je skroz dobar.
* U hrvatskom knjiž. jeziku, "ju" nije pravilno. Trebali bismo uvijek koristiti "je" iako većina ljudi zna što znači i jedno i drugo.
* Fusnota 1 ima pleonazam Iako..., ali... i nalazi se na prvoj stranici iako je referenca na drugoj.
* U primjeru となりのいえ, riječ となり pripada klasi imenica koja se službeno pojavljuje dosta kasnije, možda bi bilo bolje zamijeniti to imenom neke osobe ili slično. Isto ide i za あそこ.
* Ne smiješ iskoristiti です, to je lekcija iza. Pokušaj primjere zakomplicirati nizovima の-ova. Sasvim je u redu da stvari budu jednostavne, imaj na umu da su to ljudi koji ~2 tjedna koriste hiraganu.
* U _...opisuje se sa imenicom stolica..._, _sa_ ti zapravo smeta jer implicira da se imenice _visina_ i _stolica_ zajedno opisuju nečim trećim. U hrvatskom je suptilna razlika u značenju instrumentala, sa i bez _sa_, dobar minimalan primjer je _Igram se s prijateljem._ vs. _Igram se prijateljem._

Uglavnom, zagrabila si puno gradiva, probaj to malo pojednostavniti :)

**Comment by zludosan** [comment]
- ~~Pod tu lekciju bi ušlo nešto osnovno o imenicama (da su nepromjenjive, nema roda broja i padeža itd, neke osnovne simpa stvari)~~
To sam ubacila jednu rečenicu iz Tomislavovog ex-listića da nam radni listić ostane simpatičan.

- ~~bitno da odabereš riječi koje su korisne i česte~~

- ~~Točan prijevod これ, それ i あれ na hrvatski je ovo, to i ono.~~

- ~~U hrvatskom knjiž. jeziku, "ju" nije pravilno~~

- ~~Fusnota 1 ima pleonazam~~

- ~~riječ となり pripada klasi imenica koja se službeno pojavljuje dosta kasnije~~

- ~~Ne smiješ iskoristiti です, to je lekcija iza. Pokušaj primjere zakomplicirati nizovima の~~

- ~~opisuje se sa imenicom stolica~~

- Podcrtane neke bitne stvari za uočiti.
- Dodani novi primjer za vježbu.

Pa poluknite malo kad imate cajta...

**Comment by tmamic** [comment]
Pročitao sam i na brzinu popravio sićušne stvari tipa suptilno promašene gramatičke izraze i slično. Jedina stvar koju bi još trebala promijeniti na listiću su zadaci za vježbu. Naime, Količina novih riječi na listiću je jako velika - na početku listića je tablica novih riječi, ali njihova frekvencija pojavljivanja u ostatku japanskog teksta nije baš velika.

To samo po sebi nije loše, ali ovo je doslovno prva lekcija u kojoj očekujemo od polaznika da čitaju japanske riječi, svi će još imati tablice i tražiti po njima. Želimo da im se što više stvari ponavlja tako da mogu uočiti pravilnosti i osjetiti da su nešto skužili. Kad tek počneš, sigurno je dobar osjećaj bez gledanja se sjetiti "oh, tu riječ sam vidio 3 reda prije", to je ono na što ciljamo. Pogotovo je to bitno za vježbu na satu jer taj dio uvijek prvo probaju raditi sami. Ako nalete na hrpu novih riječi i ne budu mogli ništa dešifrirati, loše će se osjećati.

Sve primjere koje bi im možda htjela dati, ali su preteški, možeš zgurati u domaću zadaću :)

Još malo pa imaš svoj prvi listić!

**Comment by zludosan** [comment]
- Iz tablice maknula: おか、かき、か. Dodala: こうえん、うし、はな、いろ。

- Promjenila rečenice u primjerima da više koriste riječi iz tablice.

- Doradila Primjere za vježbu.

- Osim おもさ、たかさ、わたし i primjer s vremenskim oznakama koje se još ne uče, sve ostale riječi bi trebale biti iz tablice.

**Comment by tmamic** [comment]
Dobre izmjene. Maknuo sam dvostruke linije, mislio sam da si ih namjerno stavila. U format stringu si imala || umjesto |, zato su bile dvije.

**Comment by zludosan** [comment]
Dobre izmjene...
...
aliiii?

**Comment by tmamic** [comment]
Nema ali :)

Eventualno ako ti padne na pamet nešto bolje, zamijeni 3.1 nečim drugim. Kad god sastavljaš primjere, sjeti se ovog:

きた　から　きた。

_- Domagoj P. 2018._

**Comment by zludosan** [comment]
Šta je to Domagoj izjavio? :D I kak bi mi to pomoglo?

**Comment by tmamic** [comment]
Dobra je motivacija da smisliš dobre primjere. Samo se zapitaš _je li ovo nešto što bi on odobrio?_ i ako je, ne staviš to.

**Comment by zludosan** [comment]
Hahahahahaha!!!
Okej, drugim riječima, ne zafrkavati jadne učenike.  Budem nešto osmisila da to zamjenim. :D

**Comment by tmamic** [comment]
Kad si gotova, zovi @Erebus25 za završnu promjenu pa ako on ne nađe zamjerki, slobodno zatvori lekciju.

**Comment by zludosan** [comment]
Da, da...baš sam htjela reći da ne zatvaraš još. Danas bum zamjenila još onu rečenicu i jedan tipfeler. A nek ostane otvoreno, Kiki je sad u kolokvijima... pa bum pričekala.

**Comment by zludosan** [comment]
@Erebus25 Kikislav! Na tebi je red. Bez pritiska. Imaš još 10 minut da pročitaš i odgovoriš.
XD
Zez
P.S. Rečenica zamjenjena.

**Comment by tmamic** [comment]
Sad sam skužio da sam u uvodnom postu napisao _posvojna zamjenica_ umjesto _posvojna čestica_. Pardon, ispravljeno.

**Comment by tmamic** [comment]
Proširio sam wiki tablicu tako da ima linkove na dokumente vezane uz svaku lekciju. Ako si raspoložena, možeš još probati smisliti i DZ, ako bi radije sad nešto drugo, budem ja popunio kasnije.

**Comment by zludosan** [comment]
Ja'm DZ napravila... do kraja ovog tjedna.

**Comment by zludosan** [comment]
A meni je bitno da budem osoba na koju se možete osloniti i da znate da'm napravila stvar do kraja, kak spada i na vrijeme. Na ovim zadnjim dvjema stvarima još radim... >.<

**Comment by Erebus25** [comment]
Ja bih rekao da jesi već prilično pouzdana osoba, samo nemoj pretjerivat, u
smislu da ti nabija stres.

Dana 4. svibnja 2018. u 13:01 zludosan <notifications@github.com> je
napisao/la:

**Comment by zludosan** [comment]
Poštovani,
Khm, khm...znam da kasnim. （／_＼）
Al dodala sam DZ. Pa kad imate vremena da provjerite.

**Comment by tmamic** [comment]
Ne možeš kasniti ako nema rokova, ha!

U prvom je 5. pomalo neprirodan na loš način. 青の色 je pleonazam jer 青 već jest 色. Kad hoćemo reći za nešto da je plavo, opisat ćemo to kao 青の, 青い ili 青色の, ali nikad 青の色.

U drugom 3. je nekako uljez u smislu da svi ostali, iako bizarni, imaju barem nekakvog smisla :)
Nek bude lubenica prijateljeve mačke ili nešto uvjerljivije.

**Comment by tmamic** [comment]
Slava grožđanim kukcima. Smatrajmo ovu lekciju riješenom zasad. Naravno, u bilo kojem trenutku se možeš vratiti na nju i prepravljati ako ti nešto padne na pamet, ali mislim da je dovoljno dobra za upotrebu.
