### ISSUE TITLE
[lekcija] Osobne zamjenice i ljudi

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#15]
Ciljevi:
* naučiti osnove pristojnog oslovljavanja ljudi (da ne bude 呼び捨て isl)
* osobne zamjenice - pregled i koju je kad u redu koristiti, naglasak na to koje su univerzalne
* razne titule za ljude i zašto je to važno
* čestice と i や za nabrajanje

Napomene:
* spomenuti da su neke titule samo nastavci na imena, a neke i riječi za sebe (npr. 先生, 社長 itd)

**Comment by zludosan** [comment]
[Radni listić](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/004_osobne_zamjenice_i_oslovljavanje_ljudi_%E3%82%84_%E3%81%A8/release/004_osobne_zamjenice_i_oslovljavanje_ljudi_%E3%82%84_%E3%81%A8.pdf)
[Domaća zadaća](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/004_osobne_zamjenice_i_oslovljavanje_ljudi_%E3%82%84_%E3%81%A8/release/004_DZ.pdf)

Gotov je listić i zadaća uz njega pa Vas molim da pogledate...
Recite mi ako sam pretjerala  i recite mi ako nisam dovoljno. :)

**Comment by tmamic** [comment]
Pogledam detaljno sutra ujutro :)

**Comment by zludosan** [comment]
Na poslu ha? :) Samo ti daj...

**Comment by Erebus25** [comment]
Pa nećemo valjda trošit "svoje" vrijeme na to :D

2018-06-11 22:15 GMT+02:00 zludosan <notifications@github.com>:

**Comment by tmamic** [comment]
DZ:
* S obzirom da su ljudi u tom trenutku tek "naučili" hiraganu, možda bi bilo dobro da im staviš i jedan zadatak gdje moraju čitati neka imena i prezimena s papira koja ti se svide. Možeš im dodati i titule pa onda pitati je li ta osoba starija ili mlađa.

Listić (prijedlog promjena u branch [rev](https://github.com/Makoto-hr-jp/makoto-japanski/blob/rev/radionice/pocetni/lekcije/004_osobne_zamjenice_i_oslovljavanje_ljudi_や_と/004_osobne_zamjenice_i_oslovljavanje_ljudi_や_と.tex)):
* かれら sam izbacio jer se nije pojavilo u primjerima koji slijede, a i logički pripada u objašnjenje množine s ら i たち koje je ToDo
* てめー i きさま sam maknuo, to neka ostane na usmenoj predaji 😄
* dodao お ispred じょうさま jer se gotovo uvijek pojavljuje tako
* prebacio _Bog_ u _bog_ jer je Japancima svejedno koji je bog u pitanju, svi su im かみさま
* izbacio primjer おきゃくさまの　おくさんは　ダーク　チョコレートが　すき jer je pretežak
  * sadrži gramatiku koja se uči dva tjedna kasnije
  * sadrži katakanu koju ne znaju pročitati
* izbacio _Zbog toga njome nikad ne nabrajamo ljude._ jer nije potpuno točno - ima kolokvijalnih situacija gdje se tako nabrajaju i ljudi

Stil:
* kad koristiš vspace da prijeđeš na novu stranicu, to ti je ekvivalent stiskanja entera u wordu - možeš samo napisati \newpage
* japanski razmak je monospace i treba ga izbjegavati osim kad se i s lijeve i s desne strane nalaze japanski znakovi - inače uzrokuje ružne velike razmake u tekstu

Primjeri su jako fora, iako imaju dijelove gradiva iz budućnosti. Objašnjenja su dobra. Cjelokupna organizacija je možda malo neuredna u smislu da fali jasna hijerarhija. Ako imaš ideju kako stvari zgodnije organizirati da se vidi točno što gdje pripada i da vizualno postoje jasnije cjeline, to bi pomoglo.

**Comment by zludosan** [comment]
Uf, jesam ti dala posla... :D
Dodala na DZ, ispunila ToDo-ove, malo porihtala tekst, ali ima tu jako puno svega različitog. Trenutačno nemam  ideje kak organizirati bolje. Možda Kiki more pomoći...

Moj prvi pull request : [(čoml)](https://github.com/Makoto-hr-jp/makoto-japanski/pull/36)

**Comment by tmamic** [comment]
Pa cijela poanta je da si svi međusobno dajemo posla :)

**Comment by tmamic** [comment]
Zasad gotovo!

**Comment by tmamic** [comment]
@MarkoTurn @zludosan 
Lekciju valja prepraviti po naputcima u ovom komentaru ([link](https://github.com/Makoto-hr-jp/makoto-japanski/issues/37#issuecomment-423162929)) uz sljedeće otvorene točke:

- Korištenje 自分 kao osobne zamjenice 1. lica je u zadnje vrijeme uzelo maha. Prije se koristila u edo periodu uglavnom među vojnicima, a u modernom jeziku se u kansaiju povremeno koristi kao zamjenica za 2. lice. To sve skupa ovu upotrebu čini dosta nespretnom i trebalo bi je izbjegavati.

**Comment by MarkoTurn** [comment]
@tmamic 

Problem s ponavljanjem čestica u japanskom jeziku kod nabrajanja je što se skoro nikad ne koristi, čak ni u znanstvenim radovima koji su najjače orijentirani na pisani japanski. To je isto kao i rečenica これはペンです。koju u životu sigurno nitko još nije iskoristio osim u situacijama kad je kemijska, recimo, jako specifičnog oblika, pa ju je teško razaznati. 
Ja bih osobno ih učio odmah od početka da ne nabrajaju čestice nakon svake imenice već da ju spomenu samo jedanput u nizu. Ne treba ići u detalje zašto je to tako već samo da je, ali naravno odluka je na tebi :).

**Comment by tmamic** [comment]
@MarkoTurn Probajmo ove godine pa ćemo vidjeti kako im ide :)
@zludosan Sve si čula, jelda?

**Comment by zludosan** [comment]
Sad jesam...

**Comment by tmamic** [comment]
@Erebus25 @MarkoTurn Napravljeno je dosta promjena, molim pregled ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/004_osobne_zamjenice_i_oslovljavanje_ljudi_や_と/release/004_osobne_zamjenice_i_oslovljavanje_ljudi_や_と.pdf)).

**Comment by Erebus25** [comment]
"npr. -san, tomokisan" mi je ruzno jednostavno, ili nek budu nastavci ili
pune rijeci, s tim da bih stavio nastavke jer odmah ispod toga ima primjer
imena s nastavkom.
Jel "uchi" i za muskarce, mislio sam da je to za djecu i zene eventualno?

pon, 1. lis 2018. u 08:30 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by MarkoTurn** [comment]
@Erebus25 

Koriste svi, i žene, i djeca, rijeđe muškarci 
U mojih 11 godina staža japanskog i pričanja s japancima svih vrsta, čuo sam da svi koriste うち

**Comment by tmamic** [comment]
Pogotovo kad pričaju o "svojima".
