### ISSUE TITLE
[lekcija] Spojni glagol

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#16]
Ciljevi:
* objasniti što je to spojni glagol
* u japanskom velika frka oko pristojnosti i da zato postoje dva oblika
* postoje samo dva vremena
* kako radi negacija
* 4 osnovna oblika glagola (pr./npr. + poz./neg.) za pristojni i kolokvijalni oblik
* čestice は, が i も
* izjavne rečenice s im. predikatom

Napomene:
* objasniti nešto malo o razlici između は i が, ali ne ulaziti u detalje, reći da za to treba vremena
* zašto se は čita kao わ
* u zadacima koristiti の, や i と otprije za dodatne komplikacije

**Comment by tmamic** [comment]
Dodani ciljevi i napomene za predavanje ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/005_spojni_glagol/release/005_ciljevi_i_napomene.pdf)).

**Comment by Erebus25** [comment]
Ok izgleda.

2018-05-30 9:55 GMT+02:00 Tomislav Mamic <notifications@github.com>:

**Comment by tmamic** [comment]
Prva verzija listića nalazi se ovdje ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/005_spojni_glagol/release/005_spojni_glagol.pdf)).

@Erebus25 Molim pregled.

**Comment by Erebus25** [comment]
Izgleda ok, nisam ništa našao da ne valja.

Dana 7. lipnja 2018. u 12:38 Tomislav Mamic <notifications@github.com> je
napisao/la:

**Comment by tmamic** [comment]
Započeo sam DZ ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/005_spojni_glagol/release/005_DZ.pdf)), ali nemam ideja za još jedan zadatak. Po rasporedu bi taj tjedan trebali početi doma sami učiti katakanu pa sam za prvi stavio to. Ima netko nešto pametno?

**Comment by zludosan** [comment]
Da. Nek sami nađu neke riječi koje im se sviđaju, a pišu se u katakani. Moram će vježbat prepoznavati znakove i koristiti riječnik. Ili ako su pametni, zgooglat će jedan znak katakane i dobiti rezultate pa krenuti od tud.

**Comment by tmamic** [comment]
Ne nužno, bilo kakve ideje zadataka su dobrodošle. Ovo s traženjem riječi zvuči sasvim dobro.

**Comment by tmamic** [comment]
Dodan zadatak po prijedlogu. Molim još jedan brzi pregled svega pa bih zatvorio lekciju.

**Comment by zludosan** [comment]
1.  Nadovezivanje na kontekst - čestica も
...zasad ćemo je koristiti kad zamjenjuje kad zamjenjuje temu ili subjekt. -> mi se čini malo nerazumljivo. Pa da bude više ovak:...zasad ćemo ju koristiti na način na njome zamjenjujemo temu ili subjekt.

2. Prva stranica->Pristojnost-> Svi predikati(glagoli, pridjevi, im.), bolje bi bilo da je sve napisano punim riječima ili sve napisano skračenicama.

P.S. じゃまたろう! :smile:

**Comment by tmamic** [comment]
Je li _Zasad ćemo je koristiti u ulozi teme ili subjekta_ razumljivije? Trudim se što konciznije izražavati da bude što manje teksta.

**Comment by zludosan** [comment]
Da. Može i tak. :)

**Comment by tmamic** [comment]
Zasad onda zatvaramo ovu lekciju.

**Comment by tmamic** [comment]
@Erebus25 manje promjene na listiću, molim te pregledaj delte i njihovu neposrednu okolinu.

**Comment by Erebus25** [comment]
Izgleda ok.

sub, 22. ruj 2018. u 20:14 Tomislav Mamic <notifications@github.com>
napisao je:
