### ISSUE TITLE
[lekcija] Imenski predikat pridjeva

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#17]
Ciljevi:
* uvod u pridjeve
* vokabular - boje i oblici, recimo 20ak novih pridjeva
* razlika između い i な pridjeva
* imenski predikat - rečenice oblika *nešto* je *nekakvo*
* opisne zamjenice こんな, そんな i あんな
* vrijeme i negacija imenskog predikata - 4 osnovna oblika
* pristojni i kolokvijalni oblik

Napomene:
* pristojni oblik je mjestimično neočekivano zakompliciran - dati osvrt, ali ne gnjaviti previše
    * 白くないです vs. 白くありません
    * です za ukras u pristojnom obliku い pridjeva?
    * spomenuti i の pridjeve u cijeloj priči

**Comment by zludosan** [comment]
MOJE!

**Comment by tmamic** [comment]
Možda bi bilo dobro spomenuti i の pridjeve u cijeloj priči, a nisam ih gore naveo.

**Comment by zludosan** [comment]
@tmamic Evo, sad jesi.

**Comment by zludosan** [comment]
こんな, そんな i あんな nisu opisne zamjenice. To posebna je vrsta pridjeva koja se stavlja direktno ispred imenica bez の. Na engleskom to zovu pre-noun adjective pa bi mogli to zvati "predimenski pridjev". Kaj velite?

**Comment by tmamic** [comment]
Zovem ih opisne zamjenice jer su u hrvatskoj gramatici dio skupine "pridjevskih" zamjenica. PNA sam u nedostatku hrvatskog izraza dosad zvao "opisnice" što je nepostojeća, ali dosta opisna (he he he) riječ za pno što predstavlja. Problem s "predimenski pridjev" je dvojak - naime svaki pridjev je predimenski, a i ovo uopće nije pridjev.

Problem hrvatskog naziva PNA je nešto za što nema točnog odgovora jer kao koncept u hrvatskoj gramatici jednostavno ne postoji. Zato sam si dao slobode da te stvari jednostavno zovem "opisnice". U početku bih radije koristio naziv koji je u duhu hrvatske gramatike (opisne ili pridjevske zamjenice) da ljudima nešto više znači.

Iako realno, vjerojatno im "opisne zamjenice" i "opisnice" znači više manje isto - ništa - i treba objasniti što točno je. Ali fora s izrazom "opisne zamjenice" je što, kad te pitaju što je to, samo kažeš "zamjenice koje zamjenjuju opis".

**Comment by zludosan** [comment]
*Sigh*
Ja ću se pogubiti u tim nazivima. Vjerovat ću ti i koristiti tvoje nazive, vidim da si dosta razmišljal o tome i koncentrirat ću više na to da dobro objasnim razlike. A kak da onda nazovem imenice koje se koriste ko pridjevi tipa 緑. To nije の pridjev(ko npr. 否定), nije pridjev uopće, samo je imenica, ali ako veliš 緑の箱,na hrvatskom je to pridjev. Mislim da se to treba spomenuti u ovoj lekciji jer ima puno takvih korisnih imenica kojima možemo opisivati stvari.

**Comment by tmamic** [comment]
To je i imenica i の pridjev. Većina の i な pridjeva su i imenice, to je okej. U hrvatskom smo navikli da je jedna riječ u jednoj skupini, ali u jap. se time ne zamaraju previše - ovisno kako se koristi kažeš da je ili jedno ili drugo, a sama riječ je i jedno i drugo. Kvantnomehanički.

**Comment by tmamic** [comment]
Ma da, ionako ćemo sve prekontrolirati još barem dvaput, bitno je da ti znaš na što si mislila :)
