### ISSUE TITLE
[lekcija] Opisni oblik pridjeva

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#18]
Ciljevi:
* jednostavno opisivanje imenica (bez nizanja pridjeva)
* opisivanje ljudskih osobina -> rečenice oblika XはYが *nekakvo* -> razlika između teme i subjekta rečenice
* vokabular - dijelovi tijela
* pridjevi u opisnom obliku imaju vrijeme i negaciju!

Napomene:
* ako netko pita kako nizati pridjeve, spomenuti て oblik i reći da ćemo to kasnije naučiti
* natuknuti da je pridjev zapravo predikat i da kao takav čini potpunu rečenicu i da je to ključan dio japanske gramatike, ali neka ostane misteriozno

**Comment by tmamic** [comment]
Napisah ciljeve i napomene ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/007_pridjevi_opisni/release/007_ciljevi_i_napomene.pdf)). @Erebus25 molim pregled.

**Comment by tmamic** [comment]
Natipkao sam i sadržaj listića, ali bez zadataka za vježbu. ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/007_pridjevi_opisni/release/007_pridjevi_opisni.pdf)) Molim te pogledaj samo sadržaj pa reci kako ti se čini. Ako bude ok, dodajem i zadatke.

**Comment by Erebus25** [comment]
Ovo "ćorava" mi odudara, ali inače je ok.
Lošeg vida?

pon, 2. srp 2018. u 08:48 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
Popravih. Zadaci slijede nekad.

**Comment by tmamic** [comment]
Dodani zadaci. @Erebus25 ako valjaju, proglasit ću listić gotovim za sad i prelazim na DZ.

**Comment by Erebus25** [comment]
Zadnji zadatak, napisao si "ashi NO hayakunai".

uto, 3. srp 2018. u 09:39 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
Namjerno je の, dodao sam objašnjenje zašto u sekciji prije.

**Comment by Erebus25** [comment]
Ok onda

uto, 3. srp 2018. u 11:56 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
Dodana je DZ ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/007_pridjevi_opisni/release/007_DZ.pdf)). @Erebus25 Molim pregled :)

**Comment by Erebus25** [comment]
Izgleda ok

čet, 12. srp 2018. u 08:29 Tomislav Mamic <notifications@github.com>
napisao je:
