### ISSUE TITLE
[lekcija] Uvod u glagole

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#19]
Ciljevi:
* općeniti uvod u glagole: mjesto u rečenici, koje informacije kodiraju i kako itd
* fokus na kolokvijalne oblike glagola i zašto
* 一段 glagoli - 4 osnovna oblika
* vokabular - hrana s 食べる
* čestica を
Napomene:
* objasniti zašto se piše を, a čita お

**Comment by tmamic** [comment]
Dodani ciljevi i napomene ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/008_uvod_u_glagole/release/008_ciljevi_i_napomene.pdf)). @Erebus25 molim pregled :)

**Comment by tmamic** [comment]
Dodana prva verzija radnog listića ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/008_uvod_u_glagole/release/008_uvod_u_glagole.pdf)), @Erebus25 molim pregled :)

**Comment by Erebus25** [comment]
Meni izgleda dobro.

pon, 6. kol 2018. u 12:45 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
@Erebus25 Dodana DZ ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/008_uvod_u_glagole/release/008_DZ.pdf)).

**Comment by tmamic** [comment]
Zvjezdica je samo oznaka da je zadatak potencijalno teži od ostalih. Kanđi počinje nakon osnova glagola, lekcija 11.

**Comment by Erebus25** [comment]
Ok onda

uto, 7. kol 2018. u 16:39 Tomislav Mamic <notifications@github.com> napisao
je:
