### ISSUE TITLE
Kanji skripta

### ISSUE THREAD

**Issue by nyaamee** [Makoto-hr-jp/makoto-japanski#2]
Jedan od najvećih problema kod učenja kanjija je optimalan redosljed tako da se prolaze radikali i drugi sastavni dijelovi logičnim redosljedom; da se nadovezuju jedni na druge. Npr. da ne učimo, kao u Genkiju, 起きる prije 走る. 

Zamislila sam to ovako: da napravimo zasebnu skriptu za kanjije (radi preglednosti) koja će uključivati uvod s kratkom povijesti, razvojem i pravilima pisanja te popisom radikala s nazivima na hrvatskom, engleskom i japanskom. Inače preferiram da izbjegavamo engleski što je više moguće jer već ima hrpa materijala na tom jeziku, ali mislim da bi te nazive tu bilo dobro ostaviti radi lakšeg samostalnog rada. Za početak kanji skripta, naravno, ne treba strogo pratiti listiće (kao što budu cjelovite lekcije u udžbenicima), ali mislim da ćemo ih s vremenom dobro sinkronizirati.

Kao što sam već spomenula, Genki baš nije optimalan izvor za učenje kanjija, no [Genki+ Kanji Look and Learn](http://a.co/29q7Rpd) je prilično unaprijeđen. Koliko sam za sada vidjela, ima daleko logičniji slijed znakova te ih ima duplo više (600+), a uz sve to svaki znak ima zgodnu slikicu s mnemotehnikom. ([skenirani pdf](https://libgen.pw/item/detail/id/5a61ed163a044640a824cc19))

Još jedan izvor koji mi se učinio koristan na prvu je i [Kodansha Kanji Learner's Course](http://a.co/3DOg2Im) koji je kao neka biblija jer sadrži sve [Jōyō kanjije](https://en.wikipedia.org/wiki/J%C5%8Dy%C5%8D_kanji) i mnogo više (2300), a također bi trebao ići logičnim redosljedom i nadograđivati se. Nisam ga za sada baš puno koristila jer mi je dosta nepregledan u pdf-u zbog veličine i zato jer sam radila po Genkiju. ([skenirani pdf](https://libgen.pw/item/detail/id/1686324))

Još jedan poznati serijal je Heisigov Remebering the Kanji [1](http://a.co/9pqTK6K), [2](http://a.co/0QYLkEJ) i [3](http://a.co/1Hvohbs), no, izuzev mnemotehnika, izbjegavala bih ga jer frajer izmišlja svoje radikale i uči samo značenja cca 2k kanjija, i onda tek u 2. knjizi čitanja za iste. Ako sam dobro shvatila, njegova ideja je da se nauče svi kanjiji po značenju i onda da se tek počne učiti jezik kek

Uz sve to, mislim da bi bila jako dobra ideja da u obzir uzmemo i učestalost riječi koje ćemo pokrivati kroz kanjije, a za to imamo ovaj MultiPlusBenri [Frequency Dictionary of Japanese](https://ia800403.us.archive.org/8/items/AFrequencyDictionaryOfJapanese/A%20Frequency%20Dictionary%20of%20Japanese.pdf) s 5000 najčešćih riječi!

Za već jedno 10 godina bismo mogli imati nešto upotrebljivo :D

**Comment by Erebus25** [comment]
Rekao bih da za učenje kanjija ne trebamo skriptu za kanji, jedino da se možemo sjetit dogodine kako se radilo prije. Na knjige ih možemo uputit ako žele samostalno radit. Sviđa mi se Željkina ideja da uvodimo po 1/2 jednostavna kanjija svaki sat, jednostavno da ljudima bude normalno radit s njima.

**Comment by tmamic** [comment]
I meni se sviđa ideja da uvodimo kanđi što ranije, ali ne znam kako će ljudima ići. Morat ćemo svakako sljedeću godinu ciljati odoka pa onda prilagoditi količinu ovisno o rezultatima.

Bilo bi lijepo da ljudi početne radionice završe s recimo 100 komada.

**Comment by zludosan** [comment]
Ja nebi komplicirala s tim. Ljudi trebaju dovoljno da probaju pisati, da ih mogu zapamtiti i da ih mogu koristiti u svojim rečenicama kad dobe domaću zadaću.
Naša ciljana publika ne ide na Kanji Kentei ispit, a ako neki pokažu da su nadobudni i da žele više, onda takvim pojedincima možemo dati extra zadaću.

**Comment by tmamic** [comment]
Gotova i pripremljena skripta je jako ambiciozna stvar, ali bilo bi dobro imati neki plan napada koji ćemo moći provoditi kroz dulje vrijeme. Počnimo sa što smislenijim redoslijedom recimo prvih 50 koje bismo htjeli da ljudi nauče. Kad napravimo 50, ako zaključimo da je dobro, možemo lako proširiti na 100 i tako dalje. Bitnije je da utvrdimo nekakvu metodu po kojoj bismo to organizirali.

Pri sastavljanju poretka mislim da su bitne sljedeće stvari:

* Zabranjeno je učiti znak prije nego su naučeni svi njegovi radikali koje ima smisla učiti zasebno. Dopušteno je naučiti znak kojem su objašnjeni svi radikali osim jednog, a taj jedan je ili varijacija postojećeg ili neki nesamostalan dio.

* Svaki naučeni znak mora odmah biti upotrebljiv u barem jednoj riječi.

Dodatni bodovi bili bi:

* Upotrebljiv često (po frekvenciji, ne po broju riječi).

* Upotrebljiv u više situacija u kojima ima različita čitanja.

Kako vam se čini to kao prvi korak - napravimo listu njih 50 pa vidimo što dalje?

**Comment by zludosan** [comment]
1 | 2| ３| ４ | ５ | ６ | ７ | 8 | 9
------------ | -------------| -------------| -------------| -------------| -------------| -------------| -------------| -------------|
今 |曜|行|犬|大|食|上|一|青
日 |金|来|私|小|飲|下|二|赤
月 |水|出|休||読|右|三|白
年 |木|入|本||書|左|四|黒
明 |火|先|||話|中|五
朝 |土||||言||六
夜 |||||見||七
||||||思||八
||||||待||九
||||||買||十
||||||売
||||||作

Broj znakova: 55
Ovo je prijedlog kanji-ja napravljen prema riječima koje se često koriste na radionicama u primjerima i zadaćama. Tamo gdje je bilo više riječi istog tipa (npr. pridjevi koji opisuju boje) uzela sam one koje je najjednostavnije za napisat. Dodani su još i danu i tjednu i brojevi od 1 do 10.
Pa slobodno raspravite, ako mislite da bi neke od ovih kanjija trebalo maknuti ili zamjeniti za neki drugi.

**Comment by Erebus25** [comment]
Nije loše, ali ja bih recimo izbacio 金, 曜 jer ih ne koristimo bas van dana u tjednu, boje isto nisu bas prioritetne, dodao 父 母 女 男 人 雨 川 百 千 毎 車 子 学

**Comment by nyaamee** [comment]
Stavila bih brojeve u 1., dane u tjednu u 2., a ovo vremenima iz 1. u 3., a ostalo mi se čini ok. Još negdje ubaciti obitelj i ljude te ove veće brojeve što je Kiki predložio i vidjeti dal se može još koji ubaciti da se dobiju neke korisne riječi (npr. imamo 先, al nemamo 生). 

Izgleda da ste me malo krivo shvatili jer nisam nigdje specificirala, no nisam ni mislila da sad odmah napravimo ultimativnu zbirku kanjija nego da ih skupljamo ovako kroz neko vrijeme i popravljamo redosljed i metodiku, i kada se nakupi neki značajniji broj, lijepo to uredimo u jedan dokument da ne bude razbacano i jao kak smo ono išli zadnji put.

**Comment by zludosan** [comment]
Nazivi stupaca(1,2,3...) nemaju veze s prioritetom. Ali ako očete možemo ih tako slagati.

**Comment by tmamic** [comment]
Ovako bih nešto predložio:
* izbaciti 夜 i 時 iz 1 dok ne nauče 人 i 寺, možemo ih staviti kasnije
* ne 曜 dok ne nauče neke jednostavnije stvari s 隹, recimo 誰
* u 3, 先 se zapravo vrlo rijetko pojavljuje, ali možemo ga staviti u paru sa 生
* Glagoli su dosta nezgodni, recimo 食 i 飲 imaju dvije iritantne varijante istog radikala, a sam radikal nije pretjerano lijep za pisati. Onda je recimo zabranjeno naučiti 言 bez 口, 話 bez 舌 i tako dalje, trebali bismo dodati radikalčiće koji fale do tih znakova i možda neke izbaciti ako vidimo da je previše.
* s bojama se ne bih žurio, problem je što rano radimo pridjeve, a znakovi su relativno složeni

Ukratko, izbor znakova mislim da je dobar, ali pojavljuju se neki koji krše one smjernice o redoslijedu učenja, pa bi trebalo takve rastaviti na sastavne dijelove.

p.s.
možete editirati svačije postove jer ste glavni

**Comment by nyaamee** [comment]
Mislim da se ne trebamo držati tih smjernica ko pijan plota jer je 時 korisniji i češći od 寺, pa ih možemo skupa napraviti, tj reći da se 時 sastoji od 日 koji smo već učili i 寺 što znači (budistički) hram. I tako dobiju znak više. 

Ne vidim problem s 食 i 飲. Sjećam se da su mi ti bili jedni od lakših, a stalno će ih viđati i pisati jer se često pojavljuju kao primjeri za 一段 i 五段 glagole.

Prije 夜, 言 i 話 možemo napraviti 入口, 出口 i 人口 pa smo riješili problem i dobili nekoliko čestih riječi.

Sjećam se da mi je bilo baš dobro u dugavama kada smo odradili hrpu tih lakših na početku jer su mi boostali moral :D

**Comment by tmamic** [comment]
Dok je god svaki dio svakog znaka kojeg učimo objašnjen, ja sam sretan čovjek :)

Što se tiče 寺 i 時, uvijek ih spominjem u setu sa 侍 jer su besplatni ako znaš 人 i 日 pa možemo tako.

**Comment by Erebus25** [comment]
Sta sad ovaj assign radi?

**Comment by Erebus25** [comment]
Pa već smo tu, zar ne? Ili si možda ja to sve umišljam *DUN-DUN-DUUUUN*

**Comment by zludosan** [comment]
**Prijedlog 2**

1 | 2| ３| ４ | ５ | ６ | ７
------------ | -------------| -------------| -------------| -------------| -------------| -------------| 
一|金|今|行|大|父|食
二|水|明|来|小|母|飲
三|木|昨|入||女|読
四|火|時|出||男|書
五|土|来|右||人|話
六|日||左||車|言
七|月||上||子|見
八|年||下||犬|待
九|||中||木|買
十|||口||本|売
百|||休|||作
千|||
万|

Broj znakova: 60
Novi prijedlog kanji-ja prema onome što smo pisali. S time da smo si postavili 50 znakova kao limit, a ovo je već 60, a ako će se uz te znakove učiti još i njihovi radikali bit će i više.
Pitanje:
1. Da li da smanjimo početni broj znakova koji će se učiti ili neka ih bude ovoliko puno?
2. Da li treba još nešto izbaciti/dodati?
3. Kojim će se poretkom učiti znakovi?
Na primjer, ja sam da se brojevi krenu raditi na lekciji 11(količina) i sedmi red zajedno s 行来入出 da se počne učiti s lekcijom 7(ichidan, tu počnu glagoli) pa na dalje.
Moram još jednom pogledati kako idu lekcije pa ću napraviti bolji prijedlog.

**Comment by tmamic** [comment]
1. Mislim da točna količina nije pretjerano bitna dok smo god na pravom redu veličine i dok znakovi imaju smisla.
2. Ne treba, mislim da je ovo dobra kolekcija. Sadrži fini asortiman osnovnih radikala, nema nijednog preteškog znaka, ali ima neke koji bi ljudima mogli biti izazov da im ne bude dosadno. Čini se kao okej uvod.
3. Pravilo koje to diktira je
>Svaki naučeni znak mora odmah biti upotrebljiv u barem jednoj riječi.

Ne moramo forsirati to da se znakovi uče onda kad se uče i prvi pojmovi u kojima se pojavljuju, dapače. Mislim da je u redu da krenemo od jednostavnijih prema složenijima i ne zamaramo se previše time da npr. kanđi za glagole (koji su odreda svi teški) radimo kad radimo glagole, što je dosta rano. Recimo 水木人子 možemo već na imenicama, 大小 kod pridjeva i tako, polako eliminirajući one jednostavnije ne držeći se strogo sadržaja lekcije.

ごめん za pdf.

**Comment by zludosan** [comment]
Onda je sljedeći korak sastaviti koji će se kanĐi učiti za vrijeme trajanje koje lekcije ili se to prepušta učitelju?

**Comment by tmamic** [comment]
Ako imaš neku viziju, slobodno popuni ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/001_popis_tema.tex)), ali ako ti i ne padne niš na pamet, budem ja kroz koji tjedan kad mi to malo odleži u glavi pa ćemo onda prekontrolirati valja li sve skupa.

**Comment by tmamic** [comment]
Pobacao sam ugrubo znakove po temama. Ljepota je što možemo smišljati primjere u kojima će se pojaviti znakovi koji nam trebaju, ali trudio sam se da ostanu povezani ili s trenutnom temom ili s nekom od ranije obrađenih.

**Comment by tmamic** [comment]
Sve vezane priče nastavimo u ([link](https://github.com/Makoto-hr-jp/makoto-japanski/issues/4)).
