### ISSUE TITLE
[lekcija] Nepravilni glagoli

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#20]
Ciljevi:
* naučiti 4 osnovna oblika glagola くる, する, いく i ある
* する glagoli besplatni
* čestica に za lokaciju (にいる/ある) i metu (にいく/くる)
* jednostavni primjeri lokacije i mete

**Comment by tmamic** [comment]
@Erebus25 Dodani ciljevi i napomene ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/009_nepravilni/release/009_ciljevi_i_napomene.pdf)).

**Comment by Erebus25** [comment]
Valjda je dobro, nisam toliko upoznat s pricicama iz gramatike/proslosti.

sri, 8. kol 2018. u 10:16 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
@Erebus25 Dodan listić ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/009_nepravilni/release/009_nepravilni.pdf).

**Comment by Erebus25** [comment]
vjezba 4. kabakaban?

čet, 9. kol 2018. u 11:58 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
Ups, popravljeno.

**Comment by Erebus25** [comment]
Ok, nisam nasao nista drugo osim toga.

čet, 9. kol 2018. u 17:16 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by tmamic** [comment]
@Erebus25 Dodana i DZ ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/009_nepravilni/release/009_DZ.pdf)).

**Comment by Erebus25** [comment]
Čini se ok.

pet, 17. kol 2018. u 12:23 Tomislav Mamic <notifications@github.com>
napisao je:
