### ISSUE TITLE
[lekcija] Prilozi

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#23]
Ciljevi:
* objasniti "prave" priloge i njihovo mjesto u rečenici - stvari tipa (ちょっと, とても itd.)
* tvorba priloga od pridjeva -> veza između pridjeva i priloga
* ispričati malo paralelno s hrvatskim, o priložnim oznakama i koje se sve informacije u njima mogu kriti
* 10ak novih priloga, još pridjeva po potrebi
* uvrstiti nove 漢字 znakove s liste (može i u DZ)

Napomene:
* ovdje DZ nema baš nekih divljih varijacija, pa je dobra prilika za dodati još vježbe starijih stvari s novim riječima
* možda dodati i gramatiku <pridjev->prilog> + する/なる, nisam siguran

**Comment by tmamic** [comment]
@Erebus25 Dodani ciljevi i njapomene ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/012_prilozi/release/012_ciljevi_i_napomene.pdf)).

**Comment by Erebus25** [comment]
OK

čet, 23. kol 2018. u 08:36 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
@Erebus25 Dovršen listić ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/012_prilozi/release/012_prilozi.pdf)).

**Comment by Erebus25** [comment]
Mora da sam nesto krivo upisao u jisho


pon, 27. kol 2018. u 09:23 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
@Erebus25 Dodao DZ. ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/012_prilozi/release/012_DZ.pdf))
