### ISSUE TITLE
Vježba čitanja za početnike

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#24]
Sutra početnici prvi put pokušavaju čitati nepoznate tekstove i odgovarati na pitanja o njima. Tradicionalno, prvi tekst za početnike bio bi neka japanska bajka od par stranica, ali to se ispostavilo kao grozna ideja. Ove godine sam natipkao neke ful jednostavne tekstiće u kojima se ne pojavljuje ništa divlje, ali ima tu i tamo ponešto nepoznato (podcrtani dijelovi) u nadi da ih neće traumatizirati. Pročitajte, probajte riješiti pa mi recite čini li vam se kao ok težina.

Fajl ([link](https://github.com/Makoto-hr-jp/makoto-japanski/files/1906385/00x_vj_citanje.pdf))

**Comment by zludosan** [comment]
Meni se čini dobro. ⭐️ 
Bit će panika možda malo kad vide papir :D . Ali je lakše nego što izgleda i budu ponosniji na sebe na kraju, ja mislim.

Ovo mi se sviđa kao ideja za zadaću i za napredne. Da svako napiše jedan paragraf teksta sa četiri pitanja. I onda to čitamo i odgovaramo uz uvjet da pitanje mora biti takvo da se ne može odgovoriti samo z da ili ne.

**Comment by tmamic** [comment]
Hmm, ako zadam temu teksta za koju će svatko napisati nešto različito, moglo bi biti i dobro. Ako dam neku blesavu temu pa svi više-manje napišu isto, bit će samo tlaka. Isprobat ću.

**Comment by Erebus25** [comment]
Ima greška kod "daisuki", 2 puta je "ki" napisan

**Comment by zludosan** [comment]
@Erebus25 U furigani?

**Comment by zludosan** [comment]
@tmamic To ti furiganu pišeš ručno?!

**Comment by tmamic** [comment]
Naravno da furiganu pišem ručno. U općenitom slučaju ne postoji algoritam koji ti može napisati furiganu, a još manje u latexu. Kad trebaš furiganu, pišeš \furigana{<kanđi>}{<tekst iznad>}, vidi makro na ln. 47 u ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/000_template.tex)).

**Comment by tmamic** [comment]
Početnici su našli još dvije greške koje mi nismo :D
Smatrajmo ovo riješenim zasad. Nije im bilo lagano za riješiti, valjda su se isprepadali tekstom.
