### ISSUE TITLE
[lekcija] Priložne oznake mjesta

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#25]
Ciljevi:
* objasniti da u jap. ne postoje prijedlozi nego njihovu ulogu obavljaju imenice
* naučiti 20ak novih riječi, pretežno imenica za lokaciju
* obavezno 上, 下, 右, 左, 前, 後ろ, 中 + još nekih češćih -> gdje se nešto nalazi
* čestice から i まで -> upute od A do B

Napomene:
* postepeno, ali jako zakomplicirati zadatke za dz - ljudima je ovo obično relativno lagano pa da se bolje izvježbaju

**Comment by tmamic** [comment]
Ovisi isključivo o glagolu. Na koji točno primjer misliš?

**Comment by Erebus25** [comment]
Ova druga grupa odmah - ie no hidari ni => desno od kuce , si napisao

pet, 7. ruj 2018. u 10:21 Tomislav Mamic <notifications@github.com> napisao
je:

**Comment by Erebus25** [comment]
Isto i za "naka ni"

pet, 7. ruj 2018. u 10:29 Kristijan Čavić <kristijan.cavic@gmail.com>
napisao je:

**Comment by Erebus25** [comment]
Ovaj drugi se cini ok


pet, 7. ruj 2018. u 10:30 Kristijan Čavić <kristijan.cavic@gmail.com>
napisao je:

**Comment by tmamic** [comment]
Popravljeno ひだりに. Nije mi jasno što i gdje ne valja s 中に.

**Comment by tmamic** [comment]
@Erebus25 Dodana DZ ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/013_pril_ozn_mjesta/release/013_DZ.pdf)). Imaš li još kakvih ideja za 3. zadatak?

**Comment by tmamic** [comment]
@Erebus25 Dodan zadatak s opisivanjem sobe. Nisam im ograničio broj riječi jer u tom trenutku sigurno neće znati puno stvari po kući pa će morati tražiti ionako.
