### ISSUE TITLE
[lekcija] Priložne oznake vremena

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#26]
Ciljevi:
* objasniti ukratko priložne imenice, bez detalja
* objasniti vremenske imenice kao podskup priložnih
* naučiti 20ak vremenskih imenica
* naučiti reći kad i od kad do kad se nešto događa

Napomene:
* objasniti što se događa s česticama i vremenskim imenicama

**Comment by tmamic** [comment]
@Erebus25 Dodani ciljevi ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/014_pril_ozn_vremena/release/014_ciljevi_i_napomene.pdf)) i listić ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/014_pril_ozn_vremena/release/014_pril_ozn_vremena.pdf)).

**Comment by Erebus25** [comment]
Čini se ok.

pet, 14. ruj 2018. u 08:29 Tomislav Mamic <notifications@github.com>
napisao je:
