### ISSUE TITLE
[lekcija] Količina

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#27]
Ciljevi:
* naučiti brojeve 1-10 po novom i starom sustavu
* naučiti što su to brojači i zašto postoje
* naučiti brojati ljude i mačke, i možda sate
* naučiti na imenice dodati informaciju o količini

Napomene:
* ovogodišnji listić možda ima korisne podsjetnike ([link](https://drive.google.com/open?id=1vTodj4tWWQR-FFM152cHp98mSobmBWCm))
* objasniti ljudima da je to puno štrebanja i da ne moraju odmah naučiti sve dobro koristiti, nek znaju da postoji i vježbaju pomalo

**Comment by tmamic** [comment]
Lekcija i ciljevi napravljeni. Na kraju sam razdvojio na dvije lekcije jer ima puno stvari na koje se treba naviknuti. @Erebus25 molim kontrolu prvog dijela ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/015_kolicina_1/release/015_kolicina.pdf)).

**Comment by Erebus25** [comment]
Gdje se vidi ovih 10000 razlike izmedu brojeva, osim kod oku i man? "svaki
sljedeći"

sri, 13. ožu 2019. u 08:36 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
S obzirom da nam tako veliki brojevi baš i ne trebaju, uvijek ćemo stati na 億, ali poslije toga idu 兆, 京 itd. Potpuni popis možeš pogledati ovdje ([link](https://transpace.jp/suuji/)).

**Comment by Erebus25** [comment]
Znam općenito, samo ako gledaš što je na papiru možda nije očito na što se
misli s tim jednim primjerom.

sri, 13. ožu 2019. u 14:19 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
Istina. Ne znam kolika je korist od toga da to učinimo očitim, spomenuo sam usput da priča bude potpuna. Hmm, vidjet ćemo.

**Comment by Erebus25** [comment]
A dobro, drugih prigovora nema.

pet, 15. ožu 2019. u 07:17 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
Dodan drugi dio o količini ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/016_kolicina_2/release/016_kolicina_2.pdf)).

**Comment by Erebus25** [comment]
Čini se ok.

pet, 15. ožu 2019. u 09:53 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
@Erebus25 naknadno je dodana i DZ. Molim te pogledaj ima li što čudno unutra pa da zatvorimo ako nema.

**Comment by Erebus25** [comment]
Jel prvi zadatak samo pomoć ili se treba i tamo nešto radit? Ne piše ništa.

čet, 18. tra 2019. u 09:16 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
U ovim lv. zadacima uvijek se implicira prijevod na drugi jezik. Zapravo su 3 zadatka, prva dva su prijevod na hrvatski, a treći je preoblikovati na jap. rečenice iz drugog zadatka.

**Comment by Erebus25** [comment]
Ok, nemam prigovora

čet, 18. tra 2019. u 13:23 Tomislav Mamic <notifications@github.com>
napisao je:
