### ISSUE TITLE
Vježba čitanja za početnike

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#28]
Tekst se nalazi ovdje ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/vj_zad/release/00y_vj_citanje_2.pdf)). U zadnji je čas što se tiče ispravljanja, ali ako netko slučajno pogleda do sutra popodne, isplatilo se. Ako ne, ispravit ćemo za sljedeću sezonu.

**Comment by Erebus25** [comment]
Kad smo vec kod toga, kako da to otvorim i sam prepravim?

Dana 20. travnja 2018. u 17:29 Kristijan Cavic <kristijan.cavic@gmail.com>
je napisao/la:

> 一 u 一緒 se bas ne vidi. Mislim da je mozda izbacit furiganu za kanjije koji
> se ponavljaju. 掴まなかった nije pristojan oblik, kad si vec to odabrao.
>

**Comment by zludosan** [comment]
Sve su rečenice u masu/desu stilu osim "一度も掴まなかった。

**Comment by Gandeloft** [comment]
Zelim se ukljuciti huehue
Samo to sa なかった sto se mene tice.  Issho meni ne izgleda cudno.
________________________________

**Comment by Gandeloft** [comment]
Zelim se ukljuciti huehue

Samo to sa なかった sto se mene tice, iako to je toliko lako za skuziti da bi jednostavo pocetnima mogao to prezentirati kao izazov, nesto da sami skuze.
Issho mi izgleda normalno.
[Image]



P.S. sori ak je ovo vec drugi mail, prvog kojeg sam poslao ne vidim u sent
________________________________

**Comment by Erebus25** [comment]
Da, na githubu je cudan "issho", ali u pdfu je ok. Promijenio sam file, ali
mi u github programu ne pokazuje promjenu?

2018-04-20 17:35 GMT+02:00 Gandeloft <notifications@github.com>:

**Comment by tmamic** [comment]
Promijenio sam command stringove fajlova tako da poštuju podmape da texstudio sam stavlja stvari na svoja mjesta, ali to ti potrga preview pdf-a ako ga dodatno ne postaviš.  Trebalo bi staviti 掴みませんでした, da.

Što se tiče 一緒, github možda ne može lijepo renderirati pdf, iako meni i tu izgleda ok. Eventualno bih ga malo horizontalno maknuo od も ispred da se furigana ne sudara s 私.

Otvaraš s bilo kojim latex editorom koji ima xelatex support, preporučljivo texstudio.

**Comment by tmamic** [comment]
Izgleda da smo zasad dobro počistili tekst pa ćemo ovo smatrati riješenim.
