### ISSUE TITLE
Teme za širenje fonda riječi

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#3]
Dosad je uobičajena praksa na radionicama bila da je traženje novih riječi izvan onog što piše na listiću prepušteno polaznicima. Pristup u udžbenicima je gotovo uvijek upravo suprotan - lekcija se vrti oko neke pričice koja gura svoje nove riječi pa makar i pod cijenu logičnog slijeda učenja gramatike (genki, tebe gledam).

Mogli bismo pokušati složiti nešto slično (tamo gdje možemo i gdje ima smisla) i povezati lekcije s nekom temom. Prednosti toga su:
* ljudi dobiju nešto širi kontekst u kojem se riječi koriste - trenutno je raspon konteksta uglavnom samo jedna rečenica
* nove riječi su grupirane po temama

Nedostaci toga su:
* koliko vidim, nema nedostataka osim što zahtjeva dosta dodatnog rada s naše strane

Kako vam se čini ideja? Treba li nam to?

**Comment by nyaamee** [comment]
Definitivno nam treba jer mi se čini da često bude puno gramatike s kojom se ne može reći kolko bi se moglo jer je vokabular slabiji. E sad, problem je s vokabularom što bi oduzeo bezveze vremena da se obrađuje na radionicama, izuzev nekih riječi koje zahtijevaju napomene (npr. 古い se koristi samo za stvari, ali ne i za bića). Mogli bismo ga uz kanjije što više raditi i to tematski (npr. obitelj, kuća, grad, priroda, škola, hrana...). Još bi bilo efektivno da se zada za zadaću napisati neki sastavčić ili prevesti rečenice za što bi se trebale nepoznate riječi potražiti na jishou. To je pogotovo dobro za početnike jer bi se osamostalili i naučili bi da se ne smije uzeti prijevod zdravo za gotovo nego pogledati napomene i primjere u rečenicama.

Samo ne smijemo upasti u zamku da se neka gramatika poveže s nekom temom (kao što to bude u udžbenicima često), nego da se stalno stara gramatika ubacuje u nove teme i stare teme u novu gramatiku.

**Comment by tmamic** [comment]
Prvih nekoliko tema imam - sigurno su obitelj, priroda, životinje i dijelovi tijela. To pokriva dio o imenicama i pridjevima. Od glagola nadalje uglavnom počinju problemi.

**Comment by zludosan** [comment]
Jedna od lekcija s glagolima može biti snalaženje u prostoru. Kako opisati gdje se nešto nalazi, kako doći do nekog mjesta ili pak reći odkud si nešto donio ili kamo si odnio. To ima dosta materijala za glagole a i jednostavnije kanji-je.
