### ISSUE TITLE
Popunjavanje tablice sadržaja lekcija

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#4]
Referenca na okvirni sadržaj: [(link)](https://github.com/tmamic/makoto-japanski/files/1724727/plan.pdf)
Tablica lekcija: ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/001_popis_tema.tex))

Dosad smo u druge dvije teme zaključili da želimo vidjeti 漢字 ranije i da nam trebaju neke teme koje ćemo moći obrađivati uz gramatiku radi bolje podloge.

Kroz sljedećih nekoliko tjedana bismo trebali popuniti tu tablicu sa što više sadržaja kako bismo sredinom sljedećeg mjeseca mogli polako početi raspoređivati posao izrade pojedinih listića.

Recept za rad je sljedeći:
* pročitati tablicu i po potrebi baciti oko na stari plan
* razmisliti koji bi 漢字 gdje dobro išao, ili koja bi tema dobro išla uz koju gramatiku
* ako ti nešto dobro padne na pamet, upisati u tablicu

Stajemo kad tablica bude _dovoljno_ puna, što god to značilo.

Ako vam se neki od unosa u tablicu ne svidi, obračunat ćemo se u komentarima :)

**Comment by Erebus25** [comment]
Kako stojiš s ovim testovima što bi trebali biti svaka 3 tjedna?

**Comment by tmamic** [comment]
Katastrofalno, nisam nijednog odradio.

**Comment by Erebus25** [comment]
Da napravimo jedan za idući tjedan? Koje lekcije bi išle u njega?

**Comment by tmamic** [comment]
Za sljedeći tjedan (ne ovu subotu nego onu iza) bi mogao ići test s て oblikom i priložnim oznakama.

**Comment by tmamic** [comment]
Tko je mislio da je dobra ideja staviti klouz išju odmah do koment... @Erebus25 otvorio sam novu temu za test ([link](https://github.com/Makoto-hr-jp/makoto-japanski/issues/5)) za sljedeću subotu i napravio kostur dokumenta.
