### ISSUE TITLE
[lekcija] Pitanja i završne čestice

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#46]
Sadržaj lekcije nalazi se ovdje ([link](https://github.com/Makoto-hr-jp/makoto-japanski/tree/master/radionice/pocetni/lekcije/017_pitanja_zavrsne_cestice)). Potrebno je:

* pregledati sve tri stavke
* provjeriti pokriva li sadržaj listića ciljeve i napomene
* provjeriti da sadržaj DZ dobro prati sadržaj listića

**Comment by Erebus25** [comment]
Čini se ok.

čet, 18. tra 2019. u 10:27 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by Erebus25** [comment]
DZ samo

čet, 18. tra 2019. u 13:26 Kristijan Čavić <kristijan.cavic@gmail.com>
napisao je:

**Comment by Erebus25** [comment]
I ostalo se čini ok.

čet, 18. tra 2019. u 13:26 Kristijan Čavić <kristijan.cavic@gmail.com>
napisao je:
