### ISSUE TITLE
[lekcija] い oblik

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#47]
Sadržaj lekcije nalazi se ovdje ([link](https://github.com/Makoto-hr-jp/makoto-japanski/tree/master/radionice/pocetni/lekcije/018_i_oblik)). Potrebno je:

* pregledati sve tri stavke
* provjeriti pokriva li sadržaj listića ciljeve i napomene
* provjeriti da sadržaj DZ dobro prati sadržaj listića

**Comment by Erebus25** [comment]
Jel treba ovaj zarez tu?   「そのえいが、もう見た」と花子さんは いった。
Većinom se ovaj oblik pojavljuje pri spajanju s pomoćnim glagolima i
pridjevima, kojih ima jako puno i sa raznim značenjima.
*s raznim značenjima

čet, 18. tra 2019. u 12:30 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
Nije nužan, ali obično je dobar stil kad izbaciš česticu. Lakše je za čitanje. Možda je stvar osobne preference, ali svakako nije krivo.

Popravljeno *s*.

**Comment by Erebus25** [comment]
To je to onda.

čet, 18. tra 2019. u 14:33 Tomislav Mamic <notifications@github.com>
napisao je:
