### ISSUE TITLE
て oblik

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#48]
Uvod u て oblik, pokriti osnovne stvari:
* tvorba gratis uz prošlost
* završavanje rečenice -> imperativ
* nizanje rečenica
* kombinacija s pomoćnim glagolom いる -> trenutno stanje

**Comment by tmamic** [comment]
@Erebus25 Listić dodan ovdje ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/019_te_oblik/release/019_te_oblik.pdf)). Molim pregled :)

**Comment by Erebus25** [comment]
4. recenica, zarez iza "molim te", inace ok


uto, 23. tra 2019. u 10:20 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
Dodan zarez.

**Comment by tmamic** [comment]
@Erebus25 Dodana DZ ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/lekcije/019_te_oblik/release/019_DZ.pdf)). Molim pregled :)

**Comment by Erebus25** [comment]
Izgleda ok.

pon, 29. tra 2019. u 07:42 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
Postoji još jedna DZ i ciljevi i napomene, ali zasad je sve bitno pregledano.
