### ISSUE TITLE
dodaci na い oblik

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#49]
Pokriti neke osnovne korisne upotrebe い oblika:
* ~たい -> izražavanje želje
* ~易い -> lako za ~
* ~難い -> teško za ~
* ~に行く / 来る -> ići / doći raditi ~
* ~はじめる -> početi ~
* ~おわる -> završiti ~

Naglasak nije toliko na preciznim značenjima i korištenju koliko na vježbi い oblika i privikavanju na prirodno izricanje stvari u jap.

**Comment by tmamic** [comment]
@Erebus25 Dodani ciljevi i listić ([link](https://github.com/Makoto-hr-jp/makoto-japanski/tree/master/radionice/pocetni/lekcije/020_i_oblik_upotrebe/release)). Molim pregled :)

**Comment by Erebus25** [comment]
Ok se čini

pet, 10. svi 2019. u 10:05 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
@Erebus25 dodana je i DZ. Molim provjeru.

**Comment by Erebus25** [comment]
Izgleda ok.

sri, 15. svi 2019. u 08:36 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
Zasad smo gotovi s ovim.
