### ISSUE TITLE
Test て oblika i priložnih oznaka za sljedeći tjedan

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#5]
Predložak testa na kojem radimo: ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/vj_zad/00z_test_te_pr_onz.tex))

Izvori:
* listići 10, 11, 12 i 13 ([link](https://drive.google.com/drive/u/0/folders/0Bz3oODAn8tywZURsOUtrVXRWODQ))
* listić 14 ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/pocetni/radni/00x_te_1.tex))

Kad radite zadatak obratite pažnju na:
* temu zadatka - precizno odabrati, ne miješati više tema osim u nekom težem primjeru
* težinu zadatka - neka svaki sljedeći primjer u zadatku bude malo teži tako da svatko može riješiti do određene granice
* pokrivenost teme - ubaciti primjere koji dobro pokrivaju razne upotrebe neke gramatike itd.
* korelaciju zadataka - ne želimo imati dva zadatka A i B takva da ako (ne)znaš riješiti A, (ne)znaš (n)i B

Obrazloženja za kriterije iznad su:
* ne želimo dati zadatak za koji treba znati previše različitih stvari jer onda pada razumijevanje zadatka i gubimo dio informacije o tome što ljudi točno ne znaju
* gradacija mora postojati da vidimo koliko su "duboko" ljudi shvatili upotrebu
* želimo testirati sve što smo naučili
* ovo je traćenje vremena i prostora na papiru

Pozivam vas sve da doprinesete barem jednim zadatkom, ako ništa onda radi vježbe. Rok za završetak ovog ispita je **petak 2. ožujka** do kraja dana. U subotu ujutro ispiti idu na ispis :)

**Comment by Erebus25** [comment]
Što smijemo stavit? Povezivanje, ~てください, ~ている, imperativ?

**Comment by tmamic** [comment]
Radi lakoće pristupa evo i pdf listića 14 ([link](https://github.com/Makoto-hr-jp/makoto-japanski/files/1750845/00x_te_1.pdf))

Sve što je u listićima je dopušteno.

**Comment by zludosan** [comment]
Započela sam listićima:([00z_test_prijedlog](makoto-japanski/radionice/pocetni/vj_zad/00z_test_prijedlog.tex))

**Comment by tmamic** [comment]
@zludosan Dodao sam tvoje zadatke u test uz neke male izmjene. Komentare o izmjenama sam dodao u tvoj fajl.

**Comment by zludosan** [comment]
Zahvaljujem. Drugi put ću bolje :)

**Comment by tmamic** [comment]
Pa bilo je sasvim dobro :)

**Comment by Erebus25** [comment]
Ja ne mogu otvorit taj test

**Comment by tmamic** [comment]
Treba ti latex. Instaliraj si miktex 2.9 i texstudio pa ćeš moći.

**Comment by tmamic** [comment]
Test je prošao i bio je odgovarajuće težine. Za drugu godinu ćemo ipak napraviti malo više zadataka :)
