### ISSUE TITLE
Dodaci na て oblik

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#50]
Isprobati sljedeće pom. glagole s て oblikom:
* ~みる -> pokus, pokušaj
* ~おく -> u pripremi za budućnost
* ~くれる -> subjekt čini za metu (kad je govornik meta)
* ~あげる -> subjekt čini za metu (kad je govornik subjekt)
* ~もらう -> subjekt dobiva od mete (po korištenju ekvivalentno くれる, ali gram. druga perspektiva)

**Comment by tmamic** [comment]
@Erebus25 dodani listić i ciljevi ([link](https://github.com/Makoto-hr-jp/makoto-japanski/tree/master/radionice/pocetni/lekcije/021_te_oblik_upotrebe/release)). Molim pregled :)

**Comment by Erebus25** [comment]
Listići izgledaju ok, sam imam par pitanja koja pošaljem naknadno.

čet, 23. svi 2019. u 08:34 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
@Erebus25 dodana i DZ pa molim pregled. Jesi li dobio/našao odgovore na pitanja?

**Comment by Erebus25** [comment]
Ne baš, pitam te na radionicama.

pon, 27. svi 2019. u 10:22 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by Erebus25** [comment]
1.c pod 1 piše suukaku
Razočaran sam s 4. pod 2

pon, 27. svi 2019. u 10:25 Kristijan Čavić <kristijan.cavic@gmail.com>
napisao je:

**Comment by tmamic** [comment]
1.c.1 popravljen, ali 4.2 će mi zasad ostati na sramotu.
