### ISSUE TITLE
[lekcija] Opisna rečenica

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#55]
Napraviti lekciju koja pokriva sljedeće teme:

* detaljniji pogled na opis u japanskom (pridjevi vs. PNA)
* teorija opisnog i predikatnog oblika
* subjekt u opisnoj rečenici: が -> の
* puno primjera opisnih rečenica
* zamke u tumačenju opisnih rečenica - formalne (lažne) i priložne imenice

**Comment by tmamic** [comment]
Ciljevi ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/srednji/lekcije/023_opisna_recenica/release/023_ciljevi_i_napomene.pdf)) i radni listić ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/srednji/lekcije/023_opisna_recenica/release/023_opisna_recenica.pdf)) su spremni za pregled.

**Comment by tmamic** [comment]
Dodana DZ ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/srednji/lekcije/023_opisna_recenica/release/023_DZ.pdf)).

**Comment by tmamic** [comment]
@Erebus25 molim pregled.

**Comment by Erebus25** [comment]
Radni listić - predikatni i opisni oblik - makni zarez iza "sve riječi koje
su mogle poslužiti kao predikat".
Dz lvl 3. - piše ほろくて


ned, 28. srp 2019. u 21:48 Tomislav Mamic <notifications@github.com>
napisao je:

**Comment by tmamic** [comment]
@Erebus25 Popravljeno, zasad dovoljno dobro.
