### ISSUE TITLE
[lekcija] Priložne imenice I

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#57]
Primjeri upotrebe za:

* ため
* はず
* つもり

**Comment by tmamic** [comment]
@Erebus25 Cijeli paket za lekciju 25 je spreman za pregled.

**Comment by Erebus25** [comment]
Čini se ok.

sri, 2. lis 2019. u 15:22 Tomislav Mamic <notifications@github.com> napisao
je:
