### ISSUE TITLE
Provjera listića 016_te_2

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#6]
Dovršio sam listić koji ćemo u subotu raditi na srednjim radionicama ([link](https://github.com/Makoto-hr-jp/makoto-japanski/blob/master/radionice/napredni/radni/016_te_2.tex)). Htio bih da ga letimično pregledate i kažete mi ako sam što zaboravio, ako je nešto teško za čitanje itd.

Ako su vam neki primjeri teški, to je okej, proći ćemo ih sve na satu. Ako su vam svi primjeri totalno preteški, to nije okej i moram razmisliti o svom daljnjem životu.

**Comment by zludosan** [comment]
Odlično 😄 . Na nekim primjerima sam se baš nasmijala.
Ova rečenica mi ima nešto što mi nije baš jasno do kraja,al o tome ćemo na radionicama.
親に家を出るよう言われてまで私は彼女と結婚した.

**Comment by Gandeloft** [comment]
Zadnji dio na listiću (てから i nadalje) mi je u potpunosti novo gradivo. To mi je super.
Što se tiče listića sve ukupno; Uz prijevod sam uspio sve razumijeti, ali bez prijevoda bi bilo puno rupa i krivo shvaćenih rečenica.
