### ISSUE TITLE
[lekcija] Pasiv

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#61]
Pokriti sljedeće teme:

* tvorba pasiva za sve glagole
* upotrebe pasiva:
** gramatički pasiv
** modalni pasiv - negodovanje / nezadovoljstvo
** jako pristojni pasiv (samo spomenuti)

**Comment by TheFirstShuShu** [comment]
This has been claimed by Shu Shu, you're uncle, do not even think about it😜👑

**Comment by Erebus25** [comment]
You're uncle?

ned, 30. lip 2019. u 13:32 TheFirstShuShu <notifications@github.com>
napisao je:

**Comment by TheFirstShuShu** [comment]
Pa ispravila sam😭

**Comment by Erebus25** [comment]
Sad vidim, ali nije mi ništa jasnije

ned, 30. lip 2019. u 18:06 TheFirstShuShu <notifications@github.com>
napisao je:

**Comment by TheFirstShuShu** [comment]
Shu Shu znači uncle na kineskom😃
