### ISSUE TITLE
Kritika listića て II i III

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#7]
Ovaj tjedan ste imali prilike isprobati listiće na satu, sad bi bilo super da ih nasamo još malo pogledate pa napišete što vam se sviđa, a što ne. Za slučaj da nemate fizičku kopiju:
([て II](https://github.com/Makoto-hr-jp/makoto-japanski/files/1779773/016_te_2.pdf))
([て III](https://github.com/Makoto-hr-jp/makoto-japanski/files/1779774/01x_te_3.pdf))

**Comment by zludosan** [comment]
- Pogledala sam listiće još jedanput i meni su bili baš dobri. Nemam nikakvih zamjerki na sadržaj. 
Ono što ja volim je to što ima puno primjera. Meni je osobno lakše razumjeti kroz primjer nego objašnjenje, a kad ima obadvoje onda nemreš fulat. Ujedno i imamo više toga za vježbati čitati pred ljudima na radionicama kad ima dosta primjera da svako ima nešto za čitati.

- Primjetila sam samo da se razmak između redova malo spošamuril na par mjesta...
Uzmi ([て II](https://github.com/Makoto-hr-jp/makoto-japanski/files/1779773/016_te_2.pdf)) na primjer, 3.stranica, gdje je rečenica "U Šibuji postoji dućan...". Razmak između te rečenice i one koju prevodi je očito manji nego na ostalim primjerima. I onda ispod opet na prvi primjer od てさえ. Nekaj se tu čudno dešava...

**Comment by tmamic** [comment]
Okej, znači to je dobar koncept za ove napredne teme :)

Što se tiče razmaka, ovo ispod Šibuje je malo sumnjivo da, to ne bi trebalo biti tako nakeljeno. Pod てさえ ne vidim problem, čini mi se da je sve na mjestu. Malo je varljivo radi razmještaja ovih sitnih redova s furiganom, iako to ne objašnjava Šibuju. Pogledat ću.

**Comment by tmamic** [comment]
Našao sam gdje je problem u Šibuji. Koristio sam \parbox da natjeram primjer na word wrap jer je predug, ali je to sprčkalo pozicioniranje u odnosu na prethodni red. Nije elegantno rješenje, ali dobar hack je u prethodno polje ubaciti \vspace što sam i napravio.

S obzirom da je listić dosta dobro primljen, zasad ćemo ga smatrati rješenim.
