### ISSUE TITLE
Prvi dio い oblika za početnike

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#8]
Ciljao sam na to da bude laganiji tjedan, da više pričamo o tome kako funkcionira pristojnost u japanskom. Sve ostale pomoćne glagole i 美味しい detalje sam ostavio za sljedeći tjedan. Natipkao sam puno teksta što je ili ok ili jako loše, to vi meni recite.

Listić se nalazi ovdje ([link](https://github.com/Makoto-hr-jp/makoto-japanski/files/1795889/015_i_1.pdf)), a ide live sljedeću subotu.

**Comment by zludosan** [comment]
- Treća rečenica za vježbu je baš biser. 
Mislim da budu se ljudi tu malo potrgali dok ne skuže, al zato jer baš ok. :)

- Druga stranica, fusnota na **svi predikatni oblici** je nepotrebna po meni. Ili treba pisati što to znači ili ne pisati ništa. Po mogućnosti ovo prvo.

- "S obzirom na povijesni razvoj jezika i kulturnu pozadinu Japana, taj pristojni govor dolazi u nekoliko varijanti koje nam iz onog na što smo navikli u hrvatskom nisu jednostavne."
Drugim riječima, Japan ima više vrsta pristojnog govora. Umjesto da se tu objašnjava kak je nama Hrvatima to strano, bolje da se spomene koje su to vrste ili da ih se kratko opiše.

Recimo:Japan ima više vrsta pristojnog govora od kojih neke ovise o tome da li želiš iskazati poštovanje prema nekome tako da drugu osobu uzvisuješ ili da sebe ponizuješ.

 Obje rečenice su iste duljine, ali druga ti daje više informacija.

**Comment by tmamic** [comment]
Ispravljeno, hvala :)

**Comment by Gandeloft** [comment]
Ja mislim da je uvođenje kanjija bez oklijevanja bolje od suprotnoga.
Uz furiganu nisam ikada imao problema, te od prvog viđenja pojedinog kanjija taj mi se počeo urezivati u pamćenje i tako se to nadograđivalo.
Ako je to što se u skriptama izbjegava koristiti kanjije problem riješen kada/gdje ja nisam bio prisutan, just say so I'll shut up, ionako je ovo sekundarno.

**Comment by tmamic** [comment]
I ja mislim da je dobra ideja naštrebati sve glagolske oblike u prvih mjesec dana :) Problem je vizualno, ljude preplavljuju informacije. Nije uopće poanta u njihovim objektivnim mogućnostima, jednostavno kad vide puno nepoznatih stvari na papiru, teže im se snaći. Početnici su japanskom tek nekoliko mjeseci, zato na početnim listićima ne tipkam kanđi za riječi koje mislim da će im biti korisne. Kad nešto napišem, onda bude riječ tipa 連用形 koju će netko nadobudan možda guglati. Sadržajne riječi koje od njih očekujem da koriste ćemo tek početi pisati tako za par tjedana kad krenemo s osnovama kanđija.

**Comment by nyaamee** [comment]
Kod tvorbe bi mogao dodati i tablicu s pregledom za 一 i 五 glagole radi jasnoće. 
Mislim da će ovi registri biti zbunjujući tako da bi mogao dodati objašnjenje da postoje modifikacije koje uzvisuju tuđe radnje i one koje umanjuju vlastite i da se istovremeno koriste u npr. razgovoru sa šefom.
Još na kraju dijela gdje govoriš o registrima govora spomeni da se taj "osnovni pristojni registar" često naziva i です/ます oblik.

**Comment by tmamic** [comment]
Dodao sam tablicu s nekoliko primjera za 一段 i 五段. Malo sam preoblikovao tekst oko pristojnosti, ali nisam ubacio priču o 謙譲語 i 敬語, to neka ostane na razini usmene predaje. Nema smisla kad još ni za napredne nisam pripremio lekcije o tome. Zamijenio sam pdf iznad novom verzijom.
