### ISSUE TITLE
Pisanje na 原稿用紙

### ISSUE THREAD

**Issue by tmamic** [Makoto-hr-jp/makoto-japanski#9]
Dovršio sam sutrašnji listić. Htio bih da ga komentirate ovdje sutra kad ga iskoristimo. Za referencu, ([link](https://github.com/Makoto-hr-jp/makoto-japanski/files/1832255/017_pisanje.pdf)).

**Comment by zludosan** [comment]
1. Prvi paragraf - Na desnoj strani prikazana je rešetka 原稿用紙 papira, preciznije gornji desni kut.  Dobro bi bilo da i tu piše (Slika 1) radi konzistentnosti.
3. Dodati zareze ->Kvadratna polja (マス) , u koja se upisuju znakovi, složena su u stupce... 
4. Naslov i ime - dodati na kraju (Slika 2)
5. Listić ima mawi problem kaj na prvoj stranici priča o jednom, dok se slika za to nalazi na drugoj stranici. Predložila bi se ovo raspodijeli na 3 stranice ovako (ako nije greda):

<table>
  <tr>
    <th colspan="2">1.str</th>
  </tr>
  <tr>
    <td colspan="2">Izgled papira<br></td>
  </tr>
  <tr>
    <td colspan="2">Naslov i ime<br></td>
  </tr>
  <tr>
    <td><i>Slika 1</i><br></td>
    <td><i>Slika 2</i><br></td>
  </tr>
  <tr>
    <th colspan="2">2.str</th>
  </tr>
  <tr>
    <td colspan="2">Odlomci</td>
  </tr>
  <tr>
    <td colspan="2">Mali znakovi<br></td>
  </tr>
  <tr>
    <td colspan="2">Točka i zarez<br></td>
  </tr>
  <tr>
    <td><i>Slika 3</i><br></td>
    <td><i>Slika 4</i><br></td>
  </tr>
  <tr>
    <th colspan="2">3.str</th>
  </tr>
  <tr>
    <td colspan="2">Monolog i dijalog<br></td>
  </tr>
  <tr>
    <td><i>Slika 5</i><br></td>
    <td><i>Slika 6</i><br></td>
  </tr>
</table>

Tekstualni opis tablice:
"1.str : Izgled papira" tekst, ispod njega "Naslov i ime" tekst, ispod njega Slika 1 i Slika 2 jedna kraj druge.
2.str: "Odlomci" tekst, ispod njega "Mali znakovi" tekst, ispod njega "Točka i zarez" tekst, ispod njega Slika 3. i Slika 4. jedna kraj druge.
3.str: "Monolog i dijalog" tekst, ispod njega Slika 5. i Slika 6. jedna kraj druge

P.S. Znam da je gnjavaža zezati se s tim, ja bi poravnala sama (ili probala), al trenutačno nebrem. Na tuđem kompu sam. :/

**Comment by tmamic** [comment]
Sve može. Ogromna je gnjavaža poravnavati slike na specifičan način jer onaj seljački način ubacivanja slika u latex prati filozofiju iz znanstvenih radova gdje je sasvim normalno da ti je slika 10 stranica dalje, ali imam razrađenu metodu za to pa neće biti prevelik problem. S obzirom da je taj listić zasad prošao, pozabavit ću se time nekad kasnije.

**Comment by tmamic** [comment]
Presložio sam listić prema tvom prijedlogu, ako je to ono što si imala na umu, možemo ga smatrati gotovim zasad. Novi izgled je stavljen u prvi post.

**Comment by zludosan** [comment]
Da,da! To je to. Odlično. :)
